### ISSUE TITLE
Wrong opacity in Christmas Gift card template

### ISSUE THREAD

**Issue by Jasseltov** [nimiq/cards#26]
The opacity of the Christmas Gift Card template is to low when printed, making the text and QR code barely readable.

**Comment by danimoh** [comment]
Hello @Jasseltov,
which browser did you use for printing?
Can you post a photo of your printed gift card (don't forget to cover or mask the QR code before posting)?

**Comment by danimoh** [comment]
Hello @Jasseltov,
I just tested it again.
The issue you reported, was already fixed in https://github.com/nimiq/cards/commit/4184e808e43f3c5058131a7c13443bc3159a401a and https://github.com/nimiq/cards/commit/87dad92b7ade34b28897a44db80d5bf7c9b0e39e  :+1:
